### PR TITLE
Fix a memory leak for the safearray

### LINKED ISSUE #22: Memory leak when getting SAFEARRAY from a COM server
Luacom can handle SAFEARRAYs, even nested SAFEARRAYS. However after transforming correctly to a Lua table, the SAFEARRAY seems to stay in memory. With bigger SAFEARRAYs and consecutive calls, memory ist being filled up quickly to 2GB, which lets break luacom with a memory exception.

Example C++ Code for a COM server method, delivering a SAFEARRAY:

```
    static TCOMCriticalSection CS;
    LPSAFEARRAY STDMETHODCALLTYPE TFooBarImpl::GetArray(long Lines)
    {
      TCOMCriticalSection::Lock Lock(CS);
      SAFEARRAYBOUND sabdBounds[1] = { {Lines, 0} };
      LPSAFEARRAY lpsaArray = SafeArrayCreate(VT_BSTR, 1, sabdBounds);
      return lpsaArray;
    }
```

and usage with Lua is

```luacom=require"luacom"
local comsrv=luacom.CreateObject("ComSrv.FooBar")
while true do
  local t=comsrv:GetArray(888)
end
```

Even if there are no valid BSTRings allocated, memory is quicklick filling up. The same would happen with VT_I4 integer elements.

### PR DESCRIPTION
**Pull request by moteus**
Fixes https://github.com/davidm/luacom/issues/22

### CODE REVIEW

File: src/library/tLuaCOMTypeHandler.cpp [hunk 1]
```diff
@@ -1359,11 +1360,19 @@ stkIndex tLuaCOMTypeHandler::get_from_array(lua_State* L,
...
+  if(FAILED(hr)) {
+    if (vt != VT_VARIANT) {
+      VariantClear(&varg);
+    }
     LUACOM_EXCEPTION(INTERNAL_ERROR);
+  }
 
   com2lua(L, varg);
 
+  if (vt != VT_VARIANT) {
```
Comment (moteus) [inline src/library/tLuaCOMTypeHandler.cpp:1372]: I have cocerns here - may be `VariantClear` shold be called without comdition.
@1linux can you easily test with safearray of variants?
